import { z } from "zod";
import type {
  Request as ExpressRequest,
  Response as ExpressResponse,
} from "express";
import { APIError } from "mongodb-rag-core/openai";
import { SomeExpressRequest } from "../../middleware";
import { getRequestId } from "../../utils";
import { GenerateResponse } from "../../processors";
import {
  makeBadRequestError,
  makeInternalServerError,
  generateZodErrorMessage,
  sendErrorResponse,
  ERROR_TYPE,
} from "./errors";

const CreateResponseRequestBodySchema = z.object({
  model: z.string(),
  instructions: z.string().optional(),
  input: z.union([
    z
      .string()
      .refine((input) => input.length > 0, "Input must be a non-empty string"),
    z
      .array(
        z.union([
          z.object({
            type: z.literal("message").optional(),
            role: z.enum(["user", "assistant", "system"]),
            content: z.string(),
          }),
          // function tool call
          z.object({
            type: z.literal("function_call"),
            id: z
              .string()
              .optional()
              .describe("Unique ID of the function tool call"),
            name: z.string().describe("Name of the function tool to call"),
            arguments: z
              .string()
              .describe(
                "JSON string of arguments passed to the function tool call"
              ),
            status: z.enum(["in_progress", "completed", "incomplete"]),
          }),
          // function tool call output
          z.object({
            type: z.literal("function_call_output"),
            id: z
              .string()
              .optional()
              .describe("The unique ID of the function tool call output"),
            call_id: z
              .string()
              .describe(
                "Unique ID of the function tool call generated by the model"
              ),
            output: z
              .string()
              .describe("JSON string of the function tool call"),
            status: z.enum(["in_progress", "completed", "incomplete"]),
          }),
        ])
      )
      .refine((input) => input.length > 0, "Input must be a non-empty array"),
  ]),
  max_output_tokens: z.number().min(0).default(1000),
  metadata: z
    .record(z.string(), z.string().max(512))
    .optional()
    .refine(
      (metadata) => Object.keys(metadata ?? {}).length <= 16,
      "Too many metadata fields. Max 16."
    ),
  previous_response_id: z
    .string()
    .optional()
    .describe("The unique ID of the previous response to the model."),
  store: z
    .boolean()
    .optional()
    .describe("Whether to store the response in the conversation.")
    .default(true),
  stream: z.literal(true, {
    errorMap: () => ({ message: "'stream' must be true" }),
  }),
  temperature: z
    .number()
    .refine((temperature) => temperature === 0, {
      message: "Temperature must be 0 or unset",
    })
    .optional()
    .describe("Temperature for the model. Defaults to 0.")
    .default(0),
  tool_choice: z
    .union([
      z.enum(["none", "only", "auto"]),
      z
        .object({
          name: z.string(),
          type: z.literal("function"),
        })
        .describe("Function tool choice"),
    ])
    .optional()
    .describe("Tool choice for the model. Defaults to 'auto'.")
    .default("auto"),
  tools: z
    .array(
      z.object({
        name: z.string(),
        description: z.string().optional(),
        parameters: z
          .record(z.string(), z.unknown())
          .describe(
            "A JSON schema object describing the parameters of the function."
          ),
      })
    )
    .optional()
    .describe("Tools for the model to use."),

  user: z.string().optional().describe("The user ID of the user."),
});

const CreateResponseRequestSchema = SomeExpressRequest.merge(
  z.object({
    headers: z.object({
      "req-id": z.string(),
    }),
    body: CreateResponseRequestBodySchema,
  })
);

export type CreateResponseRequest = z.infer<typeof CreateResponseRequestSchema>;

export interface CreateResponseRouteParams {
  generateResponse: GenerateResponse;
  supportedModels: string[];
  maxOutputTokens: number;
}

export function makeCreateResponseRoute({
  generateResponse,
  supportedModels,
  maxOutputTokens,
}: CreateResponseRouteParams) {
  return async (
    req: ExpressRequest,
    res: ExpressResponse<{ status: string }, any>
  ) => {
    const reqId = getRequestId(req);
    const headers = req.headers as Record<string, string>;

    try {
      const {
        body: { model, max_output_tokens },
      } = req;

      // --- INPUT VALIDATION ---
      const { error } = await CreateResponseRequestSchema.safeParseAsync(req);
      if (error) {
        throw makeBadRequestError({
          error: new Error(generateZodErrorMessage(error)),
          headers,
        });
      }

      // --- MODEL CHECK ---
      if (!supportedModels.includes(model)) {
        throw makeBadRequestError({
          error: new Error(`Path: body.model - ${model} is not supported.`),
          headers,
        });
      }

      // --- MAX OUTPUT TOKENS CHECK ---
      if (max_output_tokens > maxOutputTokens) {
        throw makeBadRequestError({
          error: new Error(
            `Path: body.max_output_tokens - ${max_output_tokens} is greater than the maximum allowed ${maxOutputTokens}.`
          ),
          headers,
        });
      }

      // TODO: actually implement this call
      await generateResponse({} as any);

      return res.status(200).send({ status: "ok" });
    } catch (error) {
      const standardError =
        (error as APIError)?.type === ERROR_TYPE
          ? (error as APIError)
          : makeInternalServerError({ error: error as Error, headers });

      sendErrorResponse({
        res,
        reqId,
        error: standardError,
      });
    }
  };
}
