import {
  CORE_CHATBOT_APP_ENV_VARS,
  CORE_OPENAI_RETRIEVAL_ENV_VARS,
} from "mongodb-rag-core";
import { INGEST_ENV_VARS } from "mongodb-rag-ingest";

export const PUBLIC_INGEST_MONGODB_DOT_COM_ENV_VARS = {
  MONGODB_DOT_COM_CONNECTION_URI: "",
  MONGODB_DOT_COM_DB_NAME: "",
};

export const PUBLIC_INGEST_COACHGTM_ENV_VARS = {
  MONGODB_COACH_GTM_DATABASE_NAME: "",
};

export const PUBLIC_INGEST_MONGODB_DOCS_META_ENV_VARS = {
  MONGODB_META_DATABASE_NAME: "",
};

export const INGEST_DEVCENTER_ENV_VARS = {
  DEVCENTER_CONNECTION_URI: "",
};

export const INGEST_MDBU_ENV_VARS = {
  UNIVERSITY_DATA_API_KEY: "",
};

export const PUBLIC_INGEST_ENV_VARS = {
  ...CORE_CHATBOT_APP_ENV_VARS,
  ...CORE_OPENAI_RETRIEVAL_ENV_VARS,
  ...INGEST_ENV_VARS,
  ...INGEST_DEVCENTER_ENV_VARS,
  ...INGEST_MDBU_ENV_VARS,
};
