export const CORE_ENV_VARS = {
  MONGODB_CONNECTION_URI: "",
  MONGODB_DATABASE_NAME: "",
  OPENAI_ENDPOINT: "",
  OPENAI_API_KEY: "",
  OPENAI_EMBEDDING_DEPLOYMENT: "",
  OPENAI_EMBEDDING_MODEL: "",
  OPENAI_EMBEDDING_MODEL_VERSION: "",
  OPENAI_CHAT_COMPLETION_DEPLOYMENT: "",
  OPENAI_CHAT_COMPLETION_MODEL_VERSION: "",
  VECTOR_SEARCH_INDEX_NAME: "",
  NODE_ENV: "",
};

export const URL_ENV_VARS = ["MONGODB_CONNECTION_URI", "OPENAI_ENDPOINT"]
