const MODEL_JUDGE_ENV_VARS = {
  JUDGE_LLM: "",
  JUDGE_EMBEDDING_MODEL: "",
};

export const EVAL_ENV_VARS = {
  ...MODEL_JUDGE_ENV_VARS,
};

export const ANALYZER_ENV_VARS = {
  OPENAI_ANALYZER_CHAT_COMPLETION_DEPLOYMENT: "",
};

export const TRACING_ENV_VARS = {
  ...MODEL_JUDGE_ENV_VARS,
  ...ANALYZER_ENV_VARS,
};

export const AZURE_OPENAI_ENV_VARS = {
  OPENAI_API_KEY: "",
  OPENAI_API_VERSION: "",
  OPENAI_RESOURCE_NAME: "",
};

export const PREPROCESSOR_ENV_VARS = {
  OPENAI_PREPROCESSOR_CHAT_COMPLETION_DEPLOYMENT: "",
};

export const SLACK_ENV_VARS = {
  SLACK_BOT_TOKEN: "",
  SLACK_COMMENT_CONVERSATION_ID: "",
};
