image:
  repository: node
  tag: 18

cronJobs:
  - name: scrub
    schedule: "0 6 * * *" # every day at 6am UTC
    command: ["npm", "run", "scripts:scrubMessages"]
    env:
      MONGODB_DATABASE_NAME: docs-chatbot-prod
    envSecrets:
      MONGODB_CONNECTION_URI: docs-chatbot-prod
    resources:
      # guaranteed amount of resources
      requests:
        cpu: 100m
        memory: 2Gi
      # maximum allowed resources
      limits:
        cpu: 500m
        memory: 5Gi
    backoffLimit: 3

  - name: analyze
    schedule: "0 7 * * *" # every day at 7am UTC
    command: ["npm", "run", "scripts:analyzeMessages"]
    env:
      MONGODB_DATABASE_NAME: docs-chatbot-prod
      OPENAI_CHAT_COMPLETION_MODEL_VERSION: 2023-06-01-preview
      OPENAI_VERIFIED_ANSWER_EMBEDDING_DEPLOYMENT: "docs-chatbot-embedding-ada-002"
      OPENAI_RETRIEVAL_EMBEDDING_DEPLOYMENT: "text-embedding-3-small"
    envSecrets:
      MONGODB_CONNECTION_URI: docs-chatbot-prod
      OPENAI_ENDPOINT: docs-chatbot-prod
      OPENAI_API_KEY: docs-chatbot-prod
      OPENAI_CHAT_COMPLETION_DEPLOYMENT: docs-chatbot-prod
    resources:
      # guaranteed amount of resources
      requests:
        cpu: 100m
        memory: 2Gi
      # maximum allowed resources
      limits:
        cpu: 500m
        memory: 5Gi
    backoffLimit: 3

  - name: materialize-scrubbed-message-stats
    schedule: "0 8 * * *"
    command: ["npm", "run", "scripts:materializeScrubbedMessagesStats:latest"]
    env:
      MONGODB_DATABASE_NAME: docs-chatbot-prod
    envSecrets:
      MONGODB_CONNECTION_URI: docs-chatbot-prod
    resources:
      requests:
        cpu: 100m
        memory: 2Gi
      limits:
        cpu: 500m
        memory: 5Gi
    backoffLimit: 2

  - name: find-faq
    schedule: "0 8 * * *" # every day at 8am UTC
    command: ["npm", "run", "scripts:findFaq"]
    env:
      FROM_DATABASE_NAME: docs-chatbot-prod
      TO_DATABASE_NAME: prod-analysis
      TO_FAQ_COLLECTION_NAME: faq
    envSecrets:
      FROM_CONNECTION_URI: prod-analysis
      TO_CONNECTION_URI: prod-analysis
    resources:
      # guaranteed amount of resources
      requests:
        cpu: 100m
        memory: 2Gi
      # maximum allowed resources
      limits:
        cpu: 500m
        memory: 5Gi
    backoffLimit: 3

# Alerts
defaultAlerts:
  enabled: true
  email: "chatbot-alerts@mongodb.com"
