image:
  repository: node
  tag: 18

cronJobs:
  - name: scrub
    schedule: "0 6 * * *" # every day at 6am UTC
    command: ["npm", "run", "scripts:scrubMessages"]
    env:
      MONGODB_DATABASE_NAME: docs-chatbot-staging
    envSecrets:
      MONGODB_CONNECTION_URI: docs-chatbot-staging
    resources:
      # guaranteed amount of resources
      requests:
        cpu: 100m
        memory: 2Gi
      # maximum allowed resources
      limits:
        cpu: 500m
        memory: 5Gi
    backoffLimit: 3

  - name: analyze
    schedule: "0 7 * * *" # every day at 7am UTC
    command: ["npm", "run", "scripts:analyzeMessages"]
    env:
      MONGODB_DATABASE_NAME: docs-chatbot-staging
      OPENAI_CHAT_COMPLETION_MODEL_VERSION: 2023-06-01-preview
    envSecrets:
      MONGODB_CONNECTION_URI: docs-chatbot-staging
      OPENAI_ENDPOINT: docs-chatbot-staging
      OPENAI_API_KEY: docs-chatbot-staging
      OPENAI_VERIFIED_ANSWER_EMBEDDING_DEPLOYMENT: "docs-chatbot-embedding-ada-002"
      OPENAI_RETRIEVAL_EMBEDDING_DEPLOYMENT: "text-embedding-3-small"
      OPENAI_CHAT_COMPLETION_DEPLOYMENT: docs-chatbot-staging
    resources:
      # guaranteed amount of resources
      requests:
        cpu: 100m
        memory: 2Gi
      # maximum allowed resources
      limits:
        cpu: 500m
        memory: 5Gi
    backoffLimit: 3

  - name: materialize-scrubbed-message-stats
    schedule: "0 8 * * *" # every day at 8am UTC
    command: ["npm", "run", "scripts:materializeScrubbedMessagesStats:latest"]
    env:
      MONGODB_DATABASE_NAME: docs-chatbot-staging
    envSecrets:
      MONGODB_CONNECTION_URI: docs-chatbot-staging
    resources:
      requests:
        cpu: 100m
        memory: 2Gi
      limits:
        cpu: 500m
        memory: 5Gi
    backoffLimit: 2

  - name: clean-up-test-databases-dev
    schedule: 0 8 * * SUN
    command: ["npm", "run", "scripts:removeTestDatabases"]
    envSecrets:
      # dev cluster
      MONGODB_CONNECTION_URI: docs-chatbot-scripts-admin-dev
    resources:
      requests:
        cpu: 100m
        memory: 2Gi
      limits:
        cpu: 500m
        memory: 5Gi
    backoffLimit: 3

  - name: clean-up-test-databases-test
    schedule: 0 9 * * SUN
    command: ["npm", "run", "scripts:removeTestDatabases"]
    envSecrets:
      # test cluster
      MONGODB_CONNECTION_URI: docs-chatbot-scripts-admin-test
    resources:
      requests:
        cpu: 100m
        memory: 2Gi
      limits:
        cpu: 500m
        memory: 5Gi
    backoffLimit: 3

# Alerts
defaultAlerts:
  enabled: true
  email: "chatbot-alerts@mongodb.com"
