image:
  repository: node
  tag: 18

cronJobs:
  - name: materialize-scrubbed-message-stats
    schedule: "0 8 * * *" # every day at 8am UTC
    command: ["npm", "run", "scripts:materializeScrubbedMessagesStats:latest"]
    env:
      MONGODB_DATABASE_NAME: docs-chatbot-staging
    envSecrets:
      MONGODB_CONNECTION_URI: docs-chatbot-staging
    resources:
      requests:
        cpu: 100m
        memory: 2Gi
      limits:
        cpu: 500m
        memory: 5Gi
    backoffLimit: 2

  - name: clean-up-test-databases-dev
    schedule: 0 8 * * SUN
    command: ["npm", "run", "scripts:removeTestDatabases"]
    envSecrets:
      # dev cluster
      MONGODB_CONNECTION_URI: docs-chatbot-scripts-admin-dev
    resources:
      requests:
        cpu: 100m
        memory: 2Gi
      limits:
        cpu: 500m
        memory: 5Gi
    backoffLimit: 3

  - name: clean-up-test-databases-test
    schedule: 0 9 * * SUN
    command: ["npm", "run", "scripts:removeTestDatabases"]
    envSecrets:
      # test cluster
      MONGODB_CONNECTION_URI: docs-chatbot-scripts-admin-test
    resources:
      requests:
        cpu: 100m
        memory: 2Gi
      limits:
        cpu: 500m
        memory: 5Gi
    backoffLimit: 3

  - name: verify-sources-have-pages-staging
    schedule: "0 0 * * *" # every day at midnight UTC
    command: "npm run scripts:verifyPagesInSources"
    env:
      MONGODB_DATABASE_NAME: docs-chatbot-staging
    envSecrets:
      MONGODB_CONNECTION_URI: docs-chatbot-staging
    resources:
      requests:
        cpu: 100m
        memory: 2Gi
      limits:
        cpu: 500m
        memory: 5Gi
    backoffLimit: 2

  - name: process-citations-for-metrics
    schedule: "0 1 * * *" # every day at 1 AM UTC
    command: ["npm", "run", "scripts:getLLMAnswers"]
    env:
      MONGODB_DATABASE_NAME: docs-chatbot-staging
      PROFOUND_API_URL: https://api.tryprofound.com/v1
      PROFOUND_API_KEY_NAME: education-ai
    envSecrets:
      MONGODB_CONNECTION_URI: docs-chatbot-staging
      PROFOUND_API_KEY: docs-chatbot-staging
      PROFOUND_CATALOG_ID_EDU: docs-chatbot-staging
    resources:
      requests:
        cpu: 100m
        memory: 2Gi
      limits:
        cpu: 500m
        memory: 5Gi
    backoffLimit: 2

# Alerts
defaultAlerts:
  enabled: true
  email: "chatbot-alerts@mongodb.com"
