export const CORE_OPENAI_CONNECTION_ENV_VARS = {
  OPENAI_ENDPOINT: "",
  OPENAI_API_KEY: "",
  OPENAI_API_VERSION: "",
};

export const CORE_OPENAI_CHAT_COMPLETION_ENV_VARS = {
  ...CORE_OPENAI_CONNECTION_ENV_VARS,
  OPENAI_CHAT_COMPLETION_DEPLOYMENT: "",
};

export const BRAINTRUST_ENV_VARS = {
  BRAINTRUST_API_KEY: "",
  BRAINTRUST_ENDPOINT: "",
};
