service:
  targetPort: 3000

env:
  PORT: 3000
  OPENAI_EMBEDDING_MODEL: text-embedding-ada-002
  OPENAI_EMBEDDING_MODEL_VERSION: 2023-03-15-preview
  MONGODB_DATABASE_NAME: docs-chatbot-prod
  VECTOR_SEARCH_INDEX_NAME: default
  OPENAI_CHAT_COMPLETION_MODEL_VERSION: 2023-06-01-preview
  ALLOWED_ORIGINS: https://mongodb.com,https://www.mongodb.com
  NODE_ENV: production

envSecrets:
  MONGODB_CONNECTION_URI: docs-chatbot-prod
  OPENAI_ENDPOINT: docs-chatbot-prod
  OPENAI_API_KEY: docs-chatbot-prod
  OPENAI_EMBEDDING_DEPLOYMENT: docs-chatbot-prod
  OPENAI_CHAT_COMPLETION_DEPLOYMENT: docs-chatbot-prod

ingress:
  enabled: true
  hosts:
    - chat-server.docs.prod.corp.mongodb.com

resources:
  limits:
    memory: 1Gi
    cpu: 1
  requests:
    memory: 500Mi
    cpu: 500m
autoscaling:
  apiVersion: autoscaling/v2
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0 # scaleUp immediately if conditions met
      policies:
        # 100% of the currently running replicas may at most be added every 60s
        - type: Percent
          value: 100
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 60 # to prevent flapping, scale down after 60s
      policies:
        # At most 1 pod can be removed every 60s
        - type: Pods
          value: 1
          periodSeconds: 60
