service:
  targetPort: 3000

env:
  PORT: 3000
  OPENAI_EMBEDDING_MODEL: text-embedding-ada-002
  OPENAI_EMBEDDING_MODEL_VERSION: 2023-03-15-preview
  MONGODB_DATABASE_NAME: docs-chatbot-staging
  VECTOR_SEARCH_INDEX_NAME: default
  OPENAI_CHAT_COMPLETION_MODEL_VERSION: 2023-06-01-preview
  NODE_ENV: staging

envSecrets:
  MONGODB_CONNECTION_URI: docs-chatbot-staging
  OPENAI_ENDPOINT: docs-chatbot-staging
  OPENAI_API_KEY: docs-chatbot-staging
  OPENAI_EMBEDDING_DEPLOYMENT: docs-chatbot-staging
  OPENAI_CHAT_COMPLETION_DEPLOYMENT: docs-chatbot-staging

ingress:
  enabled: true
  hosts:
    - chat-server.docs.staging.corp.mongodb.com

resources:
  limits:
    memory: 1300Mi
  requests:
    memory: 1100Mi
