image:
  repository: node
  tag: 18

cronJobs:
  - name: upload-docs-dataset
    schedule: "0 6 * * 6" # every Saturday at 6am UTC
    command: ["npm", "run", "uploadContentDatasetToHuggingFace"]
    env:
      MONGODB_DATABASE_NAME: docs-chatbot-prod
      HUGGINGFACE_DOCS_CONTENT_REPO: mongodb-eai/docs
    envSecrets:
      MONGODB_CONNECTION_URI: docs-chatbot-prod
      HUGGINGFACE_ACCESS_TOKEN: docs-chatbot-prod
    resources:
      # guaranteed amount of resources
      requests:
        cpu: 500m
        memory: 2Gi
      # maximum allowed resources
      limits:
        cpu: 1
        memory: 5Gi
    backoffLimit: 3

  - name: upload-code-example-dataset
    schedule: "0 8 * * 6" # every Saturday at 8am UTC
    command: ["npm", "run", "uploadCodeExampleDatasetToHuggingFace"]
    env:
      MONGODB_DATABASE_NAME: docs-chatbot-prod
      OPENAI_API_VERSION: "2024-06-01"
      HUGGINGFACE_DOCS_CODE_EXAMPLES_REPO: mongodb-eai/code-examples
      OPENAI_CHAT_COMPLETION_DEPLOYMENT: gpt-4o-mini
    envSecrets:
      MONGODB_CONNECTION_URI: docs-chatbot-prod
      HUGGINGFACE_ACCESS_TOKEN: docs-chatbot-prod
      OPENAI_ENDPOINT: docs-chatbot-prod
      OPENAI_API_KEY: docs-chatbot-prod
    resources:
      # guaranteed amount of resources
      requests:
        cpu: 500m
        memory: 2Gi
      # maximum allowed resources
      limits:
        cpu: 1
        memory: 5Gi
    backoffLimit: 3
