import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  main: [
    "index",
    {
      type: "link",
      label: "OpenAPI Specification",
      href: "/server/openapi",
    },
    "ui",
    "data-sources",
    {
      type: "doc",
      label: "Framework (deprecated)",
      id: "framework",
    },
    {
      type: "category",
      label: "API Reference",
      collapsible: true,
      collapsed: true,
      link: {
        type: "generated-index",
        title: "API Reference",
        description:
          "This section contains full generated API reference documentation.",
        slug: "/reference/",
      },
      items: [
        {
          "mongodb-chatbot-ui": [
            {
              type: "autogenerated",
              dirName: "reference/ui",
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
