image:
  repository: node
  tag: 18

cronJobs:
  - name: scrub
    schedule: "0 6 * * *" # every day at 6am UTC
    command: ["node", "./build/scrubMessages.js"]
    env:
      MONGODB_DATABASE_NAME: docs-chatbot-prod
    envSecrets:
      MONGODB_CONNECTION_URI: docs-chatbot-prod
    resources:
      # guaranteed amount of resources
      requests:
        cpu: 100m
        memory: 2Gi
      # maximum allowed resources
      limits:
        cpu: 500m
        memory: 5Gi

  - name: analyze
    schedule: "0 7 * * *" # every day at 7am UTC
    command: ["node", "./build/analyzeMessages.js"]
    env:
      MONGODB_DATABASE_NAME: docs-chatbot-prod
      OPENAI_CHAT_COMPLETION_MODEL_VERSION: 2023-06-01-preview
    envSecrets:
      MONGODB_CONNECTION_URI: docs-chatbot-prod
      OPENAI_ENDPOINT: docs-chatbot-prod
      OPENAI_API_KEY: docs-chatbot-prod
      OPENAI_EMBEDDING_DEPLOYMENT: docs-chatbot-prod
      OPENAI_CHAT_COMPLETION_DEPLOYMENT: docs-chatbot-prod
    resources:
      # guaranteed amount of resources
      requests:
        cpu: 100m
        memory: 2Gi
      # maximum allowed resources
      limits:
        cpu: 500m
        memory: 5Gi

# Alerts
defaultAlerts:
  enabled: true
  email: "chatbot-alerts@mongodb.com"
